package com.google.android.gms.internal;

import android.content.Context;
import android.support.v4.view.accessibility.AccessibilityEventCompat;
import com.facebook.appevents.AppEventsConstants;
import com.facebook.internal.NativeProtocol;
import com.google.android.exoplayer.C0989C;
import com.google.android.exoplayer.ExoPlayer.Factory;
import com.google.android.exoplayer.chunk.FormatEvaluator.AdaptiveEvaluator;
import com.google.android.exoplayer.hls.HlsChunkSource;
import com.google.android.gms.ads.internal.zzu;
import com.mp3download.zingmp3.BuildConfig;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

@zzji
public final class zzdr {
    public static final zzdn<String> zzbcw;
    public static final zzdn<String> zzbcx;
    public static final zzdn<Boolean> zzbcy;
    public static final zzdn<String> zzbcz;
    public static final zzdn<Boolean> zzbda;
    public static final zzdn<String> zzbdb;
    public static final zzdn<Boolean> zzbdc;
    public static final zzdn<Boolean> zzbdd;
    public static final zzdn<String> zzbde;
    public static final zzdn<Boolean> zzbdf;
    public static final zzdn<String> zzbdg;
    public static final zzdn<String> zzbdh;
    public static final zzdn<String> zzbdi;
    public static final zzdn<Boolean> zzbdj;
    public static final zzdn<Integer> zzbdk;
    public static final zzdn<String> zzbdl;
    public static final zzdn<String> zzbdm;
    public static final zzdn<Integer> zzbdn;
    public static final zzdn<Integer> zzbdo;
    public static final zzdn<Integer> zzbdp;
    public static final zzdn<Integer> zzbdq;
    public static final zzdn<Long> zzbdr;
    public static final zzdn<Long> zzbds;
    public static final zzdn<Integer> zzbdt;
    public static final zzdn<Boolean> zzbdu;
    public static final zzdn<String> zzbdv;
    public static final zzdn<Long> zzbdw;
    public static final zzdn<Boolean> zzbdx;
    public static final zzdn<Long> zzbdy;
    public static final zzdn<Boolean> zzbdz;
    public static final zzdn<Integer> zzbea;
    public static final zzdn<Long> zzbeb;
    public static final zzdn<Boolean> zzbec;
    public static final zzdn<Boolean> zzbed;
    public static final zzdn<String> zzbee;
    public static final zzdn<Boolean> zzbef;
    public static final zzdn<Boolean> zzbeg;
    public static final zzdn<Float> zzbeh;
    public static final zzdn<String> zzbei;
    public static final zzdn<String> zzbej;
    public static final zzdn<Boolean> zzbek;
    public static final zzdn<Boolean> zzbel;
    public static final zzdn<Boolean> zzbem;
    public static final zzdn<String> zzben;
    public static final zzdn<String> zzbeo;
    public static final zzdn<String> zzbep;
    public static final zzdn<Boolean> zzbeq;
    public static final zzdn<String> zzber;
    public static final zzdn<Boolean> zzbes;
    public static final zzdn<Boolean> zzbet;
    public static final zzdn<Boolean> zzbeu;
    public static final zzdn<Integer> zzbev;
    public static final zzdn<Integer> zzbew;
    public static final zzdn<Integer> zzbex;
    public static final zzdn<Integer> zzbey;
    public static final zzdn<Integer> zzbez;
    public static final zzdn<Boolean> zzbfa;
    public static final zzdn<Integer> zzbfb;
    public static final zzdn<Boolean> zzbfc;
    public static final zzdn<Integer> zzbfd;
    public static final zzdn<Integer> zzbfe;
    public static final zzdn<String> zzbff;
    public static final zzdn<String> zzbfg;
    public static final zzdn<Boolean> zzbfh;
    public static final zzdn<Boolean> zzbfi;
    public static final zzdn<Long> zzbfj;
    public static final zzdn<String> zzbfk;
    public static final zzdn<String> zzbfl;
    public static final zzdn<Boolean> zzbfm;
    public static final zzdn<Boolean> zzbfn;
    public static final zzdn<Boolean> zzbfo;
    public static final zzdn<String> zzbfp;
    public static final zzdn<Boolean> zzbfq;
    public static final zzdn<Boolean> zzbfr;
    public static final zzdn<Integer> zzbfs;
    public static final zzdn<Boolean> zzbft;
    public static final zzdn<String> zzbfu;
    public static final zzdn<Boolean> zzbfv;
    public static final zzdn<String> zzbfw;
    public static final zzdn<String> zzbfx;
    public static final zzdn<Long> zzbfy;
    public static final zzdn<Boolean> zzbfz;
    public static final zzdn<Long> zzbga;
    public static final zzdn<Long> zzbgb;
    public static final zzdn<Boolean> zzbgc;
    public static final zzdn<String> zzbgd;
    public static final zzdn<Boolean> zzbge;
    public static final zzdn<Long> zzbgf;
    public static final zzdn<Boolean> zzbgg;
    public static final zzdn<Boolean> zzbgh;
    public static final zzdn<String> zzbgi;
    public static final zzdn<String> zzbgj;
    public static final zzdn<Integer> zzbgk;
    public static final zzdn<Integer> zzbgl;
    public static final zzdn<Integer> zzbgm;
    public static final zzdn<String> zzbgn;
    public static final zzdn<String> zzbgo;
    public static final zzdn<String> zzbgp;
    public static final zzdn<String> zzbgq;
    public static final zzdn<Boolean> zzbgr;
    public static final zzdn<Boolean> zzbgs;
    public static final zzdn<String> zzbgt;
    public static final zzdn<Long> zzbgu;
    public static final zzdn<Boolean> zzbgv;
    public static final zzdn<Long> zzbgw;
    public static final zzdn<Boolean> zzbgx;
    public static final zzdn<Boolean> zzbgy;
    public static final zzdn<Boolean> zzbgz;
    public static final zzdn<Boolean> zzbha;
    public static final zzdn<Boolean> zzbhb;
    public static final zzdn<Boolean> zzbhc;
    public static final zzdn<Boolean> zzbhd;
    public static final zzdn<Boolean> zzbhe;
    public static final zzdn<String> zzbhf;
    public static final zzdn<Long> zzbhg;
    public static final zzdn<Boolean> zzbhh;
    public static final zzdn<Boolean> zzbhi;
    public static final zzdn<Long> zzbhj;
    public static final zzdn<Long> zzbhk;
    public static final zzdn<Boolean> zzbhl;
    public static final zzdn<Long> zzbhm;
    public static final zzdn<String> zzbhn;
    public static final zzdn<Boolean> zzbho;
    public static final zzdn<String> zzbhp;
    public static final zzdn<Boolean> zzbhq;
    public static final zzdn<Boolean> zzbhr;
    public static final zzdn<String> zzbhs;
    public static final zzdn<Boolean> zzbht;
    public static final zzdn<String> zzbhu;
    public static final zzdn<Boolean> zzbhv;
    public static final zzdn<Boolean> zzbhw;
    public static final zzdn<String> zzbhx;
    public static final zzdn<Boolean> zzbhy;
    public static final zzdn<String> zzbhz;
    public static final zzdn<Boolean> zzbia;
    public static final zzdn<String> zzbib;
    public static zzdn<Boolean> zzbic;
    public static zzdn<String> zzbid;
    public static final zzdn<String> zzbie;
    public static final zzdn<Boolean> zzbif;
    public static final zzdn<Boolean> zzbig;
    public static final zzdn<Boolean> zzbih;
    public static final zzdn<Boolean> zzbii;
    public static final zzdn<Boolean> zzbij;
    public static final zzdn<String> zzbik;
    public static final zzdn<Boolean> zzbil;
    public static final zzdn<Boolean> zzbim;
    public static final zzdn<Boolean> zzbin;
    public static final zzdn<Boolean> zzbio;
    public static final zzdn<Boolean> zzbip;
    public static final zzdn<Boolean> zzbiq;
    public static final zzdn<String> zzbir;
    public static final zzdn<String> zzbis;
    public static final zzdn<String> zzbit;
    public static final zzdn<Long> zzbiu;
    public static final zzdn<Boolean> zzbiv;
    public static final zzdn<Boolean> zzbiw;
    public static final zzdn<String> zzbix;
    public static final zzdn<String> zzbiy;
    public static final zzdn<Boolean> zzbiz;
    public static final zzdn<String> zzbja;
    public static final zzdn<Boolean> zzbjb;
    public static final zzdn<Boolean> zzbjc;
    public static final zzdn<Boolean> zzbjd;
    public static final zzdn<Integer> zzbje;
    public static final zzdn<String> zzbjf;
    public static final zzdn<String> zzbjg;
    public static final zzdn<Boolean> zzbjh;
    public static final zzdn<Boolean> zzbji;
    public static final zzdn<Boolean> zzbjj;
    public static final zzdn<Boolean> zzbjk;
    public static final zzdn<Boolean> zzbjl;
    public static final zzdn<Long> zzbjm;
    public static final zzdn<Integer> zzbjn;
    public static final zzdn<Integer> zzbjo;
    public static final zzdn<Boolean> zzbjp;
    public static final zzdn<String> zzbjq;
    public static final zzdn<Long> zzbjr;
    public static final zzdn<String> zzbjs;
    public static final zzdn<Long> zzbjt;
    public static final zzdn<String> zzbju;
    public static final zzdn<Boolean> zzbjv;
    public static final zzdn<String> zzbjw;
    public static final zzdn<Long> zzbjx;
    public static final zzdn<String> zzbjy;
    public static final zzdn<String> zzbjz;
    public static final zzdn<String> zzbka;
    public static final zzdn<String> zzbkb;
    public static final zzdn<String> zzbkc;
    public static final zzdn<String> zzbkd;
    public static final zzdn<String> zzbke;
    public static final zzdn<Long> zzbkf;
    public static final zzdn<Boolean> zzbkg;
    public static final zzdn<Boolean> zzbkh;
    public static final zzdn<Boolean> zzbki;
    public static final zzdn<Long> zzbkj;
    public static final zzdn<String> zzbkk;
    public static final zzdn<Long> zzbkl;
    public static final zzdn<Boolean> zzbkm;
    public static final zzdn<Boolean> zzbkn;
    public static final zzdn<Integer> zzbko;
    public static final zzdn<Long> zzbkp;
    public static final zzdn<Boolean> zzbkq;
    public static final zzdn<Boolean> zzbkr;
    public static final zzdn<Boolean> zzbks;
    public static final zzdn<Long> zzbkt;
    public static final zzdn<Boolean> zzbku;
    public static final zzdn<Boolean> zzbkv;
    public static final zzdn<Boolean> zzbkw;
    public static final zzdn<Boolean> zzbkx;
    public static final zzdn<String> zzbky;
    public static final zzdn<String> zzbkz;
    public static final zzdn<String> zzbla;
    public static final zzdn<String> zzblb;
    public static final zzdn<Integer> zzblc;
    public static final zzdn<Integer> zzbld;
    public static final zzdn<Boolean> zzble;
    public static final zzdn<Boolean> zzblf;

    /* renamed from: com.google.android.gms.internal.zzdr.1 */
    class C12901 implements Callable<Void> {
        final /* synthetic */ Context zzang;

        C12901(Context context) {
            this.zzang = context;
        }

        public /* synthetic */ Object call() throws Exception {
            return zzdo();
        }

        public Void zzdo() {
            zzu.zzgy().initialize(this.zzang);
            return null;
        }
    }

    static {
        zzbcw = zzdn.zza(0, "gads:sdk_core_experiment_id");
        zzbcx = zzdn.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        zzbcy = zzdn.zza(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        zzbcz = zzdn.zza(0, "gads:request_builder:singleton_webview_experiment_id");
        zzbda = zzdn.zza(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
        zzbdb = zzdn.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
        zzbdc = zzdn.zza(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        zzbdd = zzdn.zza(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        zzbde = zzdn.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
        zzbdf = zzdn.zza(0, "gads:block_autoclicks", Boolean.valueOf(false));
        zzbdg = zzdn.zza(0, "gads:block_autoclicks_experiment_id");
        zzbdh = zzdn.zzb(0, "gads:prefetch:experiment_id");
        zzbdi = zzdn.zza(0, "gads:spam_app_context:experiment_id");
        zzbdj = zzdn.zza(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        zzbdk = zzdn.zza(1, "gads:http_url_connection_factory:timeout_millis", (int) AdaptiveEvaluator.DEFAULT_MIN_DURATION_FOR_QUALITY_INCREASE_MS);
        zzbdl = zzdn.zza(1, "gads:video_exo_player:version", AppEventsConstants.EVENT_PARAM_VALUE_YES);
        zzbdm = zzdn.zza(0, "gads:video_stream_cache:experiment_id");
        zzbdn = zzdn.zza(1, "gads:video_stream_cache:limit_count", 5);
        zzbdo = zzdn.zza(1, "gads:video_stream_cache:limit_space", (int) AccessibilityEventCompat.TYPE_VIEW_CONTEXT_CLICKED);
        zzbdp = zzdn.zza(1, "gads:video_stream_exo_allocator:segment_size", (int) NativeProtocol.MESSAGE_GET_ACCESS_TOKEN_REQUEST);
        zzbdq = zzdn.zza(1, "gads:video_stream_exo_cache:buffer_size", (int) AccessibilityEventCompat.TYPE_VIEW_CONTEXT_CLICKED);
        zzbdr = zzdn.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
        zzbds = zzdn.zza(1, "gads:video_stream_cache:notify_interval_millis", 1000);
        zzbdt = zzdn.zza(1, "gads:video_stream_cache:connect_timeout_millis", (int) AdaptiveEvaluator.DEFAULT_MIN_DURATION_FOR_QUALITY_INCREASE_MS);
        zzbdu = zzdn.zza(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        zzbdv = zzdn.zza(1, "gads:video:metric_frame_hash_times", BuildConfig.FLAVOR);
        zzbdw = zzdn.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
        zzbdx = zzdn.zza(1, "gads:video:force_watermark", Boolean.valueOf(false));
        zzbdy = zzdn.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
        zzbdz = zzdn.zza(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
        zzbea = zzdn.zza(1, "gads:video:spinner:scale", 4);
        zzbeb = zzdn.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
        zzbec = zzdn.zza(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
        zzbed = zzdn.zza(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
        zzbee = zzdn.zzb(0, "gads:spam_ad_id_decorator:experiment_id");
        zzbef = zzdn.zza(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        zzbeg = zzdn.zza(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
        zzbeh = zzdn.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
        zzbei = zzdn.zza(0, "gads:ad_id_app_context:experiment_id");
        zzbej = zzdn.zzb(0, "gads:looper_for_gms_client:experiment_id");
        zzbek = zzdn.zza(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        zzbel = zzdn.zza(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        zzbem = zzdn.zza(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        zzben = zzdn.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        zzbeo = zzdn.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        zzbep = zzdn.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        zzbeq = zzdn.zza(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        zzber = zzdn.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        zzbes = zzdn.zza(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        zzbet = zzdn.zza(1, "gads:use_adx_javascript_adapter", Boolean.valueOf(false));
        zzbeu = zzdn.zza(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        zzbev = zzdn.zza(0, "gads:content_length_weight", 1);
        zzbew = zzdn.zza(0, "gads:content_age_weight", 1);
        zzbex = zzdn.zza(0, "gads:min_content_len", 11);
        zzbey = zzdn.zza(0, "gads:fingerprint_number", 10);
        zzbez = zzdn.zza(0, "gads:sleep_sec", 10);
        zzbfa = zzdn.zza(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
        zzbfb = zzdn.zza(1, "gads:content_vertical_fingerprint_number", 100);
        zzbfc = zzdn.zza(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
        zzbfd = zzdn.zza(1, "gads:content_vertical_fingerprint_bits", 23);
        zzbfe = zzdn.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
        zzbff = zzdn.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
        zzbfg = zzdn.zza(1, "gads:content_fetch_exclude_view_tag", "none");
        zzbfh = zzdn.zza(0, "gad:app_index_enabled", Boolean.valueOf(true));
        zzbfi = zzdn.zza(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        zzbfj = zzdn.zza(0, "gads:app_index:timeout_ms", 1000);
        zzbfk = zzdn.zza(0, "gads:app_index:experiment_id");
        zzbfl = zzdn.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
        zzbfm = zzdn.zza(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        zzbfn = zzdn.zza(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        zzbfo = zzdn.zza(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        zzbfp = zzdn.zza(0, "gads:interstitial_follow_url:experiment_id");
        zzbfq = zzdn.zza(0, "gads:analytics_enabled", Boolean.valueOf(true));
        zzbfr = zzdn.zza(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        zzbfs = zzdn.zza(0, "gads:webview_cache_version", 0);
        zzbft = zzdn.zza(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
        zzbfu = zzdn.zza(1, "gads:webview_recycle:experiment_id");
        zzbfv = zzdn.zza(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
        zzbfw = zzdn.zzb(0, "gads:pan:experiment_id");
        zzbfx = zzdn.zza(1, "gads:rewarded:experiment_id");
        zzbfy = zzdn.zza(1, "gads:rewarded:adapter_timeout_ms", (long) HlsChunkSource.DEFAULT_MAX_BUFFER_TO_SWITCH_DOWN_MS);
        zzbfz = zzdn.zza(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
        zzbga = zzdn.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
        zzbgb = zzdn.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
        zzbgc = zzdn.zza(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
        zzbgd = zzdn.zza(1, "gads:ad_manager_enforce_arp_invariant:experiment_id");
        zzbge = zzdn.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
        zzbgf = zzdn.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", (long) HlsChunkSource.DEFAULT_MIN_BUFFER_TO_SWITCH_UP_MS);
        zzbgg = zzdn.zza(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        zzbgh = zzdn.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
        zzbgi = zzdn.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        zzbgj = zzdn.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        zzbgk = zzdn.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
        zzbgl = zzdn.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        zzbgm = zzdn.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        zzbgn = zzdn.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        zzbgo = zzdn.zza(1, "gads:spherical_video:vertex_shader", BuildConfig.FLAVOR);
        zzbgp = zzdn.zza(1, "gads:spherical_video:fragment_shader", BuildConfig.FLAVOR);
        zzbgq = zzdn.zza(1, "gads:spherical_video:experiment_id");
        zzbgr = zzdn.zza(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        zzbgs = zzdn.zza(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
        zzbgt = zzdn.zza(1, "gads:include_local_global_rectangles:experiment_id");
        zzbgu = zzdn.zza(1, "gads:position_watcher:throttle_ms", 200);
        zzbgv = zzdn.zza(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        zzbgw = zzdn.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        zzbgx = zzdn.zza(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        zzbgy = zzdn.zza(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        zzbgz = zzdn.zza(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        zzbha = zzdn.zza(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        zzbhb = zzdn.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        zzbhc = zzdn.zza(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        zzbhd = zzdn.zza(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
        zzbhe = zzdn.zza(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
        zzbhf = zzdn.zza(0, "gads:gmsg:video_meta:experiment_id");
        zzbhg = zzdn.zza(0, "gads:network:cache_prediction_duration_s", 300);
        zzbhh = zzdn.zza(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        zzbhi = zzdn.zza(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        zzbhj = zzdn.zza(0, "gads:ad_loader:timeout_ms", (long) HlsChunkSource.DEFAULT_PLAYLIST_BLACKLIST_MS);
        zzbhk = zzdn.zza(0, "gads:rendering:timeout_ms", (long) HlsChunkSource.DEFAULT_PLAYLIST_BLACKLIST_MS);
        zzbhl = zzdn.zza(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        zzbhm = zzdn.zza(1, "gads:gestures:task_timeout", 2000);
        zzbhn = zzdn.zza(1, "gads:gestures:encrypt_size_limit:experiment_id");
        zzbho = zzdn.zza(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
        zzbhp = zzdn.zza(1, "gads:gestures:appid:experiment_id");
        zzbhq = zzdn.zza(1, "gads:gestures:appid:enabled", Boolean.valueOf(false));
        zzbhr = zzdn.zza(0, "gads:gestures:v6:enabled", Boolean.valueOf(false));
        zzbhs = zzdn.zza(1, "gads:gestures:usb_query:experiment_id");
        zzbht = zzdn.zza(1, "gads:gestures:usb_query:enabled", Boolean.valueOf(false));
        zzbhu = zzdn.zza(1, "gads:gestures:usb_click:experiment_id");
        zzbhv = zzdn.zza(1, "gads:gestures:usb_click:enabled", Boolean.valueOf(false));
        zzbhw = zzdn.zza(1, "gads:gestures:touchinfo:enabled", Boolean.valueOf(false));
        zzbhx = zzdn.zza(1, "gads:gestures:touchinfo:experiment_id");
        zzbhy = zzdn.zza(1, "gads:gestures:clock_query:enabled", Boolean.valueOf(false));
        zzbhz = zzdn.zza(1, "gads:gestures:clock_query:experiment_id");
        zzbia = zzdn.zza(1, "gads:gestures:clock_click:enabled", Boolean.valueOf(false));
        zzbib = zzdn.zza(1, "gads:gestures:clock_click:experiment_id");
        zzbic = zzdn.zza(1, "gads:gestures:btl_click:enabled", Boolean.valueOf(false));
        zzbid = zzdn.zza(1, "gads:gestures:btl_click:experiment_id");
        zzbie = zzdn.zza(1, "gads:gestures:click_stk:experiment_id");
        zzbif = zzdn.zza(1, "gads:gestures:click_stk:enabled", Boolean.valueOf(true));
        zzbig = zzdn.zza(1, "gads:gestures:visibility:enabled", Boolean.valueOf(false));
        zzbih = zzdn.zza(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
        zzbii = zzdn.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
        zzbij = zzdn.zza(0, "gass:client:enabled", Boolean.valueOf(true));
        zzbik = zzdn.zza(0, "gass:client:experiment_id");
        zzbil = zzdn.zza(0, "gass:enabled", Boolean.valueOf(true));
        zzbim = zzdn.zza(0, "gass:enable_int_signal", Boolean.valueOf(true));
        zzbin = zzdn.zza(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        zzbio = zzdn.zza(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        zzbip = zzdn.zza(0, "gads:support_screen_shot", Boolean.valueOf(true));
        zzbiq = zzdn.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
        zzbir = zzdn.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
        zzbis = zzdn.zza(1, "gads:sdk_core_constants:experiment_id");
        zzbit = zzdn.zza(1, "gads:sdk_core_constants:caps", BuildConfig.FLAVOR);
        zzbiu = zzdn.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        zzbiv = zzdn.zza(0, "gads:js_flags:mf", Boolean.valueOf(false));
        zzbiw = zzdn.zza(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
        zzbix = zzdn.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        zzbiy = zzdn.zza(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
        zzbiz = zzdn.zza(1, "gads:singleton_webview_native", Boolean.valueOf(false));
        zzbja = zzdn.zza(1, "gads:singleton_webview_native:experiment_id");
        zzbjb = zzdn.zza(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
        zzbjc = zzdn.zza(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
        zzbjd = zzdn.zza(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
        zzbje = zzdn.zza(1, "gads:native_video_load_timeout", 10);
        zzbjf = zzdn.zza(1, "gads:native_video_load_timeout:experiment_id");
        zzbjg = zzdn.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        zzbjh = zzdn.zza(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
        zzbji = zzdn.zza(1, "gads:enable_tracking_for_native_ad_views", Boolean.valueOf(true));
        zzbjj = zzdn.zza(1, "gads:use_new_json_for_native_view_tracking", Boolean.valueOf(true));
        zzbjk = zzdn.zza(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
        zzbjl = zzdn.zza(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
        zzbjm = zzdn.zza(0, "gads:method_tracing:duration_ms", 30000);
        zzbjn = zzdn.zza(0, "gads:method_tracing:count", 5);
        zzbjo = zzdn.zza(0, "gads:method_tracing:filesize", (int) C0989C.SAMPLE_FLAG_DECODE_ONLY);
        zzbjp = zzdn.zza(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
        zzbjq = zzdn.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
        zzbjr = zzdn.zza(1, "gads:auto_location_timeout", 2000);
        zzbjs = zzdn.zzb(1, "gads:auto_location_timeout:experiment_id");
        zzbjt = zzdn.zza(1, "gads:auto_location_interval", -1);
        zzbju = zzdn.zzb(1, "gads:auto_location_interval:experiment_id");
        zzbjv = zzdn.zza(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
        zzbjw = zzdn.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        zzbjx = zzdn.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        zzbjy = zzdn.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
        zzbjz = zzdn.zza(0, "gads:afs:csa:experiment_id");
        zzbka = zzdn.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        zzbkb = zzdn.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        zzbkc = zzdn.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        zzbkd = zzdn.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        zzbke = zzdn.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        zzbkf = zzdn.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
        zzbkg = zzdn.zza(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
        zzbkh = zzdn.zza(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
        zzbki = zzdn.zza(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
        zzbkj = zzdn.zza(1, "gads:parental_controls:timeout", 2000);
        zzbkk = zzdn.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        zzbkl = zzdn.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        zzbkm = zzdn.zza(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
        zzbkn = zzdn.zza(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
        zzbko = zzdn.zza(1, "gads:cache:max_concurrent_downloads", 10);
        zzbkp = zzdn.zza(1, "gads:cache:javascript_timeout_millis", (long) HlsChunkSource.DEFAULT_MIN_BUFFER_TO_SWITCH_UP_MS);
        zzbkq = zzdn.zza(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
        zzbkr = zzdn.zza(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
        zzbks = zzdn.zza(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
        zzbkt = zzdn.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
        zzbku = zzdn.zza(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
        zzbkv = zzdn.zza(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
        zzbkw = zzdn.zza(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(false));
        zzbkx = zzdn.zza(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(false));
        zzbky = zzdn.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        zzbkz = zzdn.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        zzbla = zzdn.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        zzblb = zzdn.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        zzblc = zzdn.zza(1, "gads:drx_debug:timeout_ms", (int) Factory.DEFAULT_MIN_REBUFFER_MS);
        zzbld = zzdn.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
        zzble = zzdn.zza(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
        zzblf = zzdn.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    }

    public static void initialize(Context context) {
        zzlo.zzb(new C12901(context));
    }

    public static List<String> zzlq() {
        return zzu.zzgx().zzlq();
    }

    public static List<String> zzlr() {
        return zzu.zzgx().zzlr();
    }
}
